self_see_links:
## ur5
# - name: base_link
#   padding: .05
#   scale: 1.0
# - name: shoulder_link
#   padding: .05
#   scale: 1.0
# - name: upper_arm_link
#   padding: .05
#   scale: 1.0
# - name: forearm_link
#   padding: .05
#   scale: 1.0
- name: wrist_1_link
  padding: .05
  scale: 1.0
- name: wrist_2_link
  padding: .05
  scale: 1.0
- name: wrist_3_link
  padding: .05
  scale: 1.0

## robotiq  
- name: robotiq_arg2f_base_link
  padding: .05
  scale: 1.0
# - name: right_outer_knuckle
#   padding: .05
#   scale: 1.0
# - name: right_outer_finger
#   padding: .05
#   scale: 1.0
# - name: right_inner_knuckle
#   padding: .05
#   scale: 1.0
# - name: right_inner_finger
#   padding: .05
#   scale: 1.0
# - name: right_inner_finger_pad
#   padding: .05
#   scale: 1.0
# - name: left_outer_knuckle
#   padding: .05
#   scale: 1.0
# - name: left_outer_finger
#   padding: .05
#   scale: 1.0
# - name: left_inner_knuckle
#   padding: .05
#   scale: 1.0
# - name: left_inner_finger
#   padding: .05
#   scale: 1.0
# - name: left_inner_finger_pad
#   padding: .05
#   scale: 1.0

## test
# - name: test_link
#   padding: .05
#   scale: 1.0
